//
//  ------------------------------------------------
//  Original project: CoreDataEvolution
//  Created on 2024/10/30 by Fatbobman(东坡肘子)
//  X: @fatbobman
//  Mastodon: @fatbobman@mastodon.social
//  GitHub: @fatbobman
//  Blog: https://fatbobman.com
//  ------------------------------------------------
//  Copyright © 2024-present Fatbobman. All rights reserved.

import Foundation
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

let coreDataPrimitiveTypeNamesInOrder: [String] = [
  "String",
  "Bool",
  "Int",
  "Int16",
  "Int32",
  "Int64",
  "Float",
  "Double",
  "Decimal",
  "Date",
  "Data",
  "UUID",
  "URL",
]

let coreDataPrimitiveTypeNames: Set<String> = Set(coreDataPrimitiveTypeNamesInOrder)

func coreDataPrimitiveTypeListDescription(includeOptionals: Bool = true) -> String {
  let joined = coreDataPrimitiveTypeNamesInOrder.joined(separator: ", ")
  return includeOptionals ? "\(joined) and optionals" : joined
}

/// Returns `false` only when the macro is declared with `disableGenerateInit: true`.
func shouldGenerateInitializer(from node: AttributeSyntax) -> Bool {
  guard let argumentList = node.arguments?.as(LabeledExprListSyntax.self) else {
    return true  // Default to true if no arguments are present.
  }

  for argument in argumentList {
    if argument.label?.text == "disableGenerateInit",
      let booleanLiteral = argument.expression.as(BooleanLiteralExprSyntax.self)
    {
      return booleanLiteral.literal.text != "true"  // Return false if "disableGenerateInit" is set to true.
    }
  }
  return true  // Default to true if "disableGenerateInit" is not found or is set to false.
}

enum DeclaredAccessLevel: String {
  case open
  case `public`
  case package
  case `internal`
  case `fileprivate`
  case `private`

  var textWithTrailingSpace: String {
    switch self {
    case .internal:
      return ""
    default:
      return "\(rawValue) "
    }
  }
}

func declaredAccessLevel(from declaration: some DeclGroupSyntax) -> DeclaredAccessLevel {
  let accessLevels: [DeclaredAccessLevel] = [
    .open, .public, .package, .internal, .fileprivate, .private,
  ]
  for access in accessLevels {
    if declaration.modifiers.contains(where: { $0.name.text == access.rawValue }) {
      return access
    }
  }
  return .internal
}

/// Returns explicit access modifier text with trailing space, or empty string for implicit internal.
func accessModifierText(from declaration: some DeclGroupSyntax) -> String {
  declaredAccessLevel(from: declaration).textWithTrailingSpace
}

/// Access modifier text for protocol requirement witnesses generated by macros.
/// For `private` attached types, use `fileprivate` to satisfy witness visibility
/// across generated file-scope conformance extensions.
func witnessAccessModifierText(from declaration: some DeclGroupSyntax) -> String {
  switch declaredAccessLevel(from: declaration) {
  case .private, .fileprivate:
    return "fileprivate "
  default:
    return accessModifierText(from: declaration)
  }
}

/// Shared diagnostics emitter for macro implementations.
enum MacroDiagnosticReporter {
  static func error(
    _ message: String,
    domain: String,
    id: String = "invalid-declaration",
    in context: some MacroExpansionContext,
    node: some SyntaxProtocol
  ) {
    diagnose(
      message: message,
      severity: .error,
      domain: domain,
      id: id,
      in: context,
      node: node
    )
  }

  static func warning(
    _ message: String,
    domain: String,
    id: String = "warning",
    in context: some MacroExpansionContext,
    node: some SyntaxProtocol
  ) {
    diagnose(
      message: message,
      severity: .warning,
      domain: domain,
      id: id,
      in: context,
      node: node
    )
  }

  static func note(
    _ message: String,
    domain: String,
    id: String = "note",
    in context: some MacroExpansionContext,
    node: some SyntaxProtocol
  ) {
    diagnose(
      message: message,
      severity: .note,
      domain: domain,
      id: id,
      in: context,
      node: node
    )
  }

  private static func diagnose(
    message: String,
    severity: DiagnosticSeverity,
    domain: String,
    id: String,
    in context: some MacroExpansionContext,
    node: some SyntaxProtocol
  ) {
    let diagnosticMessage = MacroDiagnosticMessage(
      message: message,
      severity: severity,
      id: MessageID(domain: domain, id: id)
    )
    context.diagnose(Diagnostic(node: Syntax(node), message: diagnosticMessage))
  }
}

private struct MacroDiagnosticMessage: DiagnosticMessage {
  let message: String
  let severity: DiagnosticSeverity
  let id: MessageID

  var diagnosticID: MessageID { id }
}
