//
//  ------------------------------------------------
//  Original project: CoreDataEvolution
//  Created on 2026/3/5 by Fatbobman(东坡肘子)
//  X: @fatbobman
//  Mastodon: @fatbobman@mastodon.social
//  GitHub: @fatbobman
//  Blog: https://fatbobman.com
//  ------------------------------------------------
//  Copyright © 2024-present Fatbobman. All rights reserved.

import Foundation

/// Leaf field metadata emitted by `@Composition`-like codegen.
public struct CDCompositionFieldMeta: Equatable, Sendable {
  public let swiftPath: [String]
  public let persistentPath: [String]
  public let storageMethod: StorageMethod

  public init(
    swiftPath: [String],
    persistentPath: [String],
    storageMethod: StorageMethod = .default
  ) {
    self.swiftPath = swiftPath
    self.persistentPath = persistentPath
    self.storageMethod = storageMethod
  }
}

/// Contract for static composition metadata generated by `@Composition`.
public protocol CDCompositionPathProviding {
  static var __cdCompositionFieldTable: [String: CDCompositionFieldMeta] { get }
}

/// Contract for dictionary encode/decode generated by `@Composition`.
public protocol CDCompositionValueCodable: CDCompositionPathProviding {
  static func __cdDecodeComposition(from dictionary: [String: Any]) -> Self?
  var __cdEncodeComposition: [String: Any] { get }
}

/// Entry path for composition subfields, e.g. `Model.path.location.latitude`.
@dynamicMemberLookup
public struct CDCompositionPath<
  Root: CoreDataPathTable,
  Value,
  Composition: CoreDataPathDSLProviding
>: @unchecked Sendable {
  public let root: CDPath<Root, Value>

  public init(root: CDPath<Root, Value>) {
    self.root = root
  }

  public var swiftPath: [String] {
    root.swiftPath
  }

  public var persistentPath: [String] {
    root.persistentPath
  }

  public var storageMethod: StorageMethod {
    root.storageMethod
  }

  public var swiftPathKey: String {
    root.swiftPathKey
  }

  public var persistentPathKey: String {
    root.persistentPathKey
  }

  public var raw: String {
    root.raw
  }

  public subscript<Leaf>(
    dynamicMember keyPath: KeyPath<Composition.PathRoot, CDPath<Composition, Leaf>>
  ) -> CDPath<Root, Leaf> {
    let leafPath = Composition.path[keyPath: keyPath]
    return CDPath<Root, Leaf>(
      swiftPath: root.swiftPath + leafPath.swiftPath,
      persistentPath: root.persistentPath + leafPath.persistentPath,
      storageMethod: leafPath.storageMethod
    )
  }
}

/// Utility used by the model macro path-table generation step.
public enum CDCompositionTableBuilder {
  public static func makeModelFieldEntries<Composition: CDCompositionPathProviding>(
    modelSwiftPathPrefix: [String],
    modelPersistentPathPrefix: [String],
    composition: Composition.Type
  ) -> [String: CDFieldMeta] {
    var result: [String: CDFieldMeta] = [:]
    for (_, leaf) in Composition.__cdCompositionFieldTable {
      let swiftPath = modelSwiftPathPrefix + leaf.swiftPath
      let persistentPath = modelPersistentPathPrefix + leaf.persistentPath
      let key = swiftPath.joined(separator: ".")
      result[key] = CDFieldMeta(
        kind: .attribute,
        swiftPath: swiftPath,
        persistentPath: persistentPath,
        storageMethod: leaf.storageMethod,
        supportsStoreSort: true
      )
    }
    return result
  }
}
